import 'dart:async';
import 'dart:math';
import 'package:flame/game.dart';
import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';
import '../game/core/game_session.dart';
import '../game/touch_quest_game.dart';
import '../services/save_service.dart';
import '../services/firebase_service.dart';
import '../services/feedback_service.dart';
import '../services/ad_service.dart';

const cyan=Color(0xff58f9ef), gold=Color(0xffffd675), muted=Color(0xff8e9cba);
class TouchQuestApp extends StatelessWidget {
  const TouchQuestApp({super.key,required this.save});
  final SaveService save;
  @override Widget build(BuildContext context)=>MaterialApp(title:'Touch Quest',debugShowCheckedModeBanner:false,theme:ThemeData(useMaterial3:true,brightness:Brightness.dark,scaffoldBackgroundColor:const Color(0xff070c1b),colorScheme:ColorScheme.fromSeed(seedColor:cyan,brightness:Brightness.dark),fontFamily:'monospace',textTheme:const TextTheme(bodyMedium:TextStyle(color:muted)),sliderTheme:const SliderThemeData(activeTrackColor:cyan)),home:QuestShell(save:save));
}
class QuestShell extends StatefulWidget {
  const QuestShell({super.key,required this.save});
  final SaveService save;
  @override State<QuestShell> createState()=>_QuestShellState();
}
class _QuestShellState extends State<QuestShell> with WidgetsBindingObserver,SingleTickerProviderStateMixin {
  late final cloud=FirebaseService(widget.save);
  late final audio=FeedbackService(widget.save);
  late final ads=AdService.create();
  late final AnimationController animation=AnimationController(vsync:this,duration:const Duration(seconds:5))..repeat(reverse:true);
  GameSession? session;
  TouchQuestGame? game;
  String page='menu', notice='';
  int savedTaps=0;
  bool finished=false, busy=false, warning=false;
  double hudElapsed=0;
  SaveService get save=>widget.save;
  @override void initState() {super.initState(); WidgetsBinding.instance.addObserver(this); save.addListener(refresh); unawaited(setup());}
  Future<void> setup() async {await cloud.init(); await audio.init(); try {await ads.initialize();} catch(e) {debugPrint('Ads unavailable: $e');} refresh();}
  void refresh() {if(mounted) setState((){});}
  @override void dispose() {save.removeListener(refresh); WidgetsBinding.instance.removeObserver(this); animation.dispose(); game?.pauseEngine(); unawaited(audio.dispose()); ads.dispose(); super.dispose();}
  @override void didChangeAppLifecycleState(AppLifecycleState state) {if(state!=AppLifecycleState.resumed) pause();}
  void pause() {if(session?.state==RunState.playing) {session!.pause(); game!.pauseEngine(); unawaited(audio.music(false)); unawaited(checkpoint()); refresh();}}
  Future<void> checkpoint() async {final s=session; if(s==null) return; final previous=savedTaps; savedTaps=s.rawTaps; await save.record(s,previous);}
  void resume() {session!.resume(); game!.resumeEngine(); unawaited(audio.music(true)); refresh();}
  void start(GameMode mode,{int stage=0}) {
    game?.pauseEngine();
    session=GameSession(mode:mode,stage:stage,velocityPerk:save.badges.contains(15000),seed:DateTime.now().millisecondsSinceEpoch);
    savedTaps=0; hudElapsed=0; finished=false; warning=false; notice='';
    game=TouchQuestGame(session!,save,frame); page='play';
    unawaited(cloud.event('game_started',{'mode':mode.name})); if(mode==GameMode.campaign) unawaited(cloud.event('campaign_level_started',{'stage':stage}));
    unawaited(audio.music(true)); refresh();
  }
  void frame() {
    final s=session!;
    if(s.remaining<.6 && !warning) {warning=true; audio.haptic(); audio.sound('danger');}
    if((s.state==RunState.over || s.state==RunState.won) && !finished) {
      finished=true; unawaited(checkpoint()); unawaited(cloud.submit(s.toJson())); unawaited(cloud.event('game_over',{'raw_taps':s.rawTaps,'mode':s.mode.name}));
      if(s.mode==GameMode.campaign) unawaited(cloud.event(s.state==RunState.won?'campaign_level_completed':'campaign_level_failed',{'stage':s.stage}));
      audio.sound(s.state==RunState.won?'milestone':'gameover'); unawaited(audio.music(false));
    }
    // HUD has a fixed 30 Hz budget; Canvas continues at display refresh rate.
    if(s.duration-hudElapsed>=1/30 || finished) {hudElapsed=s.duration; refresh();}
  }
  void tap(Offset p) {
    final s=session!; final before=s.rawTaps; final unlocked=s.tap(p);
    if(s.rawTaps>before) {
      game!.burst(p,celebrate:unlocked.any((n)=>[1000,10000,100000].contains(n)));
      audio.tap(s.rawTaps); warning=false;
      for(final n in unlocked) {notice=milestones[n]!; audio.sound('milestone'); audio.haptic(strong:true); unawaited(cloud.event('milestone_$n')); if(n==500) unawaited(audio.music(true,overdrive:true));}
      if(unlocked.isNotEmpty || s.rawTaps%50==0) unawaited(checkpoint());
    }
    frame(); refresh();
  }
  Future<void> action(Future<void> Function() work) async {if(busy) return; setState(()=>busy=true); try {await work();} catch(e) {if(mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString()),duration:const Duration(seconds:6)));} finally {if(mounted) setState(()=>busy=false);}}
  void navigate(String next) {if(page=='play') {game?.pauseEngine(); unawaited(audio.music(false)); unawaited(checkpoint());} audio.sound('menu'); page=next; refresh();}
  @override Widget build(BuildContext context) {
    return Scaffold(body:SafeArea(child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:560),child:Column(children:[Expanded(child:AnimatedBuilder(animation:animation,builder:(context,_)=>DecoratedBox(decoration:BoxDecoration(gradient:RadialGradient(center:Alignment(.5*sin(animation.value*pi),-.6),radius:1.3,colors:const [Color(0xff202044),Color(0xff080e21)]),border:Border.symmetric(vertical:BorderSide(color:cyan.withValues(alpha:.08)))),child:page=='play'?play():page=='menu'?menu():subpage()))),Container(height:58,color:const Color(0xff0d1527),alignment:Alignment.center,child:ads.banner())])))));
  }
  Widget menu()=>LayoutBuilder(builder:(context,constraints)=>SingleChildScrollView(padding:const EdgeInsets.fromLTRB(28,24,28,20),child:ConstrainedBox(constraints:BoxConstraints(minHeight:max(0,constraints.maxHeight-44)),child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.stretch,children:[
    Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[tag('●  FINGER POWERED',cyan),const Text('VOL. 01',style:TextStyle(fontSize:10,color:muted))]),const SizedBox(height:32),
    SizedBox(height:125,child:Stack(alignment:Alignment.center,children:[Transform.rotate(angle:save.flag('reduceMotion',false)?0:(animation.value-.5)*.12,child:Container(width:106,height:106,decoration:BoxDecoration(shape:BoxShape.circle,border:Border.all(color:cyan.withValues(alpha:.35),width:2),boxShadow:[BoxShadow(color:cyan.withValues(alpha:.08),blurRadius:50,spreadRadius:15)]),child:const Icon(Icons.touch_app_rounded,color:cyan,size:67))),Positioned(right:35,top:10,child:tag('1.5s',gold)),Positioned(left:22,bottom:10,child:tag('+1',const Color(0xffbb8cff)))])),
    const Text('TOUCH',textAlign:TextAlign.center,style:TextStyle(fontSize:48,height:1,fontWeight:FontWeight.w900,letterSpacing:7,color:Colors.white)),
    const Text('QUEST',textAlign:TextAlign.center,style:TextStyle(fontSize:54,height:1.1,fontWeight:FontWeight.w900,letterSpacing:7,color:cyan,shadows:[Shadow(color:Color(0xff247e94),offset:Offset(0,4))])),
    const SizedBox(height:12),const Text('TAP. SURVIVE. ASCEND.',textAlign:TextAlign.center,style:TextStyle(fontSize:11,letterSpacing:3,color:muted)),const SizedBox(height:30),
    button('PLAY ENDLESS',()=>start(GameMode.casual),icon:Icons.bolt,color:cyan,subtitle:'One rule. Don’t stop tapping.'),const SizedBox(height:12),
    Row(children:[Expanded(child:button('CAMPAIGN',()=>navigate('campaign'),icon:Icons.explore_outlined,subtitle:'50 stages',color:const Color(0xffbb8cff))),const SizedBox(width:12),Expanded(child:button('CHAOS RUN',()=>start(GameMode.chaos),icon:Icons.whatshot_outlined,subtitle:'Expect nonsense',color:gold))]),
    const SizedBox(height:22),Row(mainAxisAlignment:MainAxisAlignment.spaceEvenly,children:[navIcon('RANKS',Icons.leaderboard_outlined,'leaderboard'),navIcon('PROFILE',Icons.person_outline,'profile'),navIcon('SETTINGS',Icons.tune,'settings')]),const SizedBox(height:24),
    Row(mainAxisAlignment:MainAxisAlignment.center,children:[stat('BEST RUN','${save.number('bestRawRun')}'),const SizedBox(width:40),stat('LIFETIME','${save.number('lifetimeTaps')}')]),const SizedBox(height:20),const Text('SIMPLE AT FIRST. RIDICULOUS FOREVER.',textAlign:TextAlign.center,style:TextStyle(fontSize:8,color:muted,letterSpacing:1.6)),
  ]))));
  Widget navIcon(String title,IconData icon,String route)=>TextButton(onPressed:()=>navigate(route),child:Column(children:[Icon(icon,color:muted,size:22),const SizedBox(height:6),Text(title,style:const TextStyle(color:muted,fontSize:9))]));
  Widget tag(String text,Color color)=>Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:6),decoration:BoxDecoration(color:color.withValues(alpha:.08),borderRadius:BorderRadius.circular(20),border:Border.all(color:color.withValues(alpha:.2))),child:Text(text,style:TextStyle(color:color,fontSize:9,letterSpacing:1)));
  Widget stat(String label,String value)=>Column(children:[Text(value,style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:4),Text(label,style:const TextStyle(color:muted,fontSize:9,letterSpacing:1))]);
  Widget button(String title,VoidCallback? onTap,{IconData? icon,Color color=cyan,String? subtitle})=>FilledButton(onPressed:onTap,style:FilledButton.styleFrom(backgroundColor:color.withValues(alpha:.11),foregroundColor:color,padding:const EdgeInsets.symmetric(horizontal:12,vertical:18),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(15),side:BorderSide(color:color.withValues(alpha:.4)))),child:Column(children:[Row(mainAxisAlignment:MainAxisAlignment.center,children:[if(icon!=null)...[Icon(icon,size:20),const SizedBox(width:7)],Flexible(child:Text(title,textAlign:TextAlign.center,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w900,letterSpacing:1)))]),if(subtitle!=null)...[const SizedBox(height:7),Text(subtitle,textAlign:TextAlign.center,style:TextStyle(fontSize:9,color:color.withValues(alpha:.65)))]]));
  Widget play() {
    final s=session!; final next=milestones.keys.firstWhere((n)=>n>s.rawTaps,orElse:()=>100000);
    return Column(children:[Container(padding:const EdgeInsets.fromLTRB(20,10,12,12),decoration:const BoxDecoration(gradient:LinearGradient(colors:[Color(0xff18364f),Color(0xff172741)])),child:Column(children:[Row(children:[Text(s.mode.name.toUpperCase(),style:const TextStyle(color:cyan,fontSize:10,letterSpacing:2)),const Spacer(),Text('BEST ${save.number('bestRawRun')}',style:const TextStyle(color:muted,fontSize:10)),IconButton(onPressed:pause,tooltip:'Pause',icon:const Icon(Icons.pause_rounded,color:cyan))]),Row(crossAxisAlignment:CrossAxisAlignment.end,children:[Text('${s.score}',style:TextStyle(fontSize:48,height:1,color:s.rawTaps>=10000?gold:Colors.white,fontWeight:FontWeight.w900)),const SizedBox(width:12),Padding(padding:const EdgeInsets.only(bottom:6),child:tag('×${s.multiplier}',gold)),const Spacer(),Text('${s.rawTaps} RAW TAPS',style:const TextStyle(color:muted,fontSize:9))]),const SizedBox(height:14),ClipRRect(borderRadius:BorderRadius.circular(8),child:LinearProgressIndicator(value:s.grace>0?1:s.remaining/1.5,minHeight:5,color:s.remaining<.6?const Color(0xffff7b91):cyan,backgroundColor:Colors.white10)),const SizedBox(height:9),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(s.grace>0?'GET READY':s.precision?'TAP THE GLOWING ZONE':'EVERY TAP RESETS 1.5s',style:const TextStyle(fontSize:8,color:muted)),Text(s.mode==GameMode.campaign?'STAGE ${s.stage+1} · ${s.rawTaps}/${s.goal}':'NEXT: $next',style:const TextStyle(fontSize:8,color:muted))])])),Expanded(child:Stack(children:[Positioned.fill(child:Listener(behavior:HitTestBehavior.opaque,onPointerDown:(e)=>tap(e.localPosition),child:GameWidget(game:game!))),if(notice.isNotEmpty && s.ages[s.highest]!=null && s.ages[s.highest]!<4) Positioned(top:18,left:12,right:12,child:IgnorePointer(child:Column(children:[tag(notice,gold),if(s.highest==700) const Text('Sponsored by absolutely nobody.',style:TextStyle(color:gold,fontSize:10)),if(s.highest==50000) const Text('We did not expect you to get here.',style:TextStyle(color:gold,fontSize:10))]))),if(s.state!=RunState.playing) Positioned.fill(child:Container(color:const Color(0xee080e21),alignment:Alignment.center,child:SingleChildScrollView(padding:const EdgeInsets.all(26),child:s.state==RunState.paused?pausePanel():overPanel())))]))]);
  }
  Widget pausePanel()=>Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Icon(Icons.pause_circle_outline,color:cyan,size:56),const SizedBox(height:16),const Text('TAKE A BREATHER',textAlign:TextAlign.center,style:TextStyle(fontSize:22,color:Colors.white,fontWeight:FontWeight.bold)),const SizedBox(height:10),const Text('Your run is safely paused.',textAlign:TextAlign.center),const SizedBox(height:24),button('RESUME',resume),const SizedBox(height:12),button('MAIN MENU',()=>navigate('menu'),color:muted)]);
  Widget overPanel() {
    final s=session!; final won=s.state==RunState.won;
    return Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[tag(won?'FINGER PROMOTED':'RUN COMPLETE',gold),const SizedBox(height:15),Text(won?'QUEST CLEARED':'GAME OVER',textAlign:TextAlign.center,style:const TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:12),Text('${s.rawTaps}',textAlign:TextAlign.center,style:const TextStyle(color:cyan,fontSize:58,fontWeight:FontWeight.w900)),const Text('REAL. PHYSICAL. TAPS.',textAlign:TextAlign.center,style:TextStyle(color:muted,fontSize:9,letterSpacing:2)),const SizedBox(height:18),Wrap(alignment:WrapAlignment.spaceEvenly,spacing:22,runSpacing:12,children:[stat('SCORE','${s.score}'),stat('SECONDS',s.duration.toStringAsFixed(1)),stat('TAPS / SEC',s.tapRate.toStringAsFixed(1)),stat('BEST','${save.number('bestRawRun')}')]),const SizedBox(height:12),Text(s.highest>0?milestones[s.highest]!:s.reason,textAlign:TextAlign.center,style:const TextStyle(color:gold,fontSize:10)),if(s.reviveCount>0) const Padding(padding:EdgeInsets.only(top:10),child:Text('REVIVED RUN · UNRANKED',textAlign:TextAlign.center,style:TextStyle(color:muted,fontSize:9))),const SizedBox(height:22),if(!won && s.reviveCount==0)...[button(ads.rewardedReady?'WATCH AD TO REVIVE':'REVIVE · NO AD AVAILABLE',ads.rewardedReady && !busy?()=>action(() async {await cloud.event('revive_offered'); final earned=await ads.reward(); if(s.revive(rewarded:earned)) {finished=false; audio.sound('revive'); await cloud.event('revive_completed'); await audio.music(true);} refresh();}):null,color:gold),const SizedBox(height:10)],button(won && s.stage<49?'NEXT STAGE':'TRY AGAIN',()=>action(() async {if(won) await ads.stageBreak(); start(s.mode,stage:won?min(49,s.stage+1):s.stage);})),const SizedBox(height:10),Row(children:[Expanded(child:button('MAIN MENU',()=>navigate('menu'),color:muted)),const SizedBox(width:10),Expanded(child:button('SHARE',()=>action(() async {await SharePlus.instance.share(ShareParams(text:'I survived ${s.rawTaps} taps in Touch Quest. Think your finger can beat mine? ${const String.fromEnvironment('GAME_URL')}'));}),color:muted))])]);
  }
  Widget subpage()=>Column(children:[Padding(padding:const EdgeInsets.all(14),child:Row(children:[IconButton(onPressed:()=>navigate('menu'),icon:const Icon(Icons.arrow_back,color:cyan)),const SizedBox(width:8),Text(page.toUpperCase(),style:const TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.bold,letterSpacing:2))])),Expanded(child:SingleChildScrollView(padding:const EdgeInsets.fromLTRB(24,0,24,28),child:switch(page){'campaign'=>campaign(),'settings'=>settings(),'profile'=>profile(),'leaderboard'=>leaderboard(),'skins'=>skins(),_=>legal()}))]);
  Widget campaign()=>Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('50 QUESTS. ONE VERY BUSY FINGER.',style:TextStyle(color:muted,fontSize:10)),const SizedBox(height:20),for(var world=0;world<worlds.length;world++)...[
    Text('${world+1}. ${worlds[world]}',style:TextStyle(color:world%2==0?cyan:gold,fontSize:16,fontWeight:FontWeight.bold)),const SizedBox(height:10),Row(children:[for(var i=0;i<5;i++) Expanded(child:Padding(padding:const EdgeInsets.all(3),child:button('${world*5+i+1}',world*5+i<=save.number('campaign')?()=>start(GameMode.campaign,stage:world*5+i):null,color:world*5+i<save.number('campaign')?gold:cyan)))]),const SizedBox(height:22)]]);
  Widget toggle(String key,String title,{bool fallback=true})=>SwitchListTile(contentPadding:EdgeInsets.zero,title:Text(title,style:const TextStyle(fontSize:13)),value:save.flag(key,fallback),onChanged:(v){unawaited(save.set(key,v)); if(key=='music') unawaited(audio.music(false)); if(key=='analytics') unawaited(cloud.setAnalytics(v));});
  Widget choose(String key,String title,List<String> values,String initial)=>ListTile(contentPadding:EdgeInsets.zero,title:Text(title,style:const TextStyle(fontSize:13)),trailing:DropdownButton<String>(value:save.choice(key,initial),items:values.map((v)=>DropdownMenuItem(value:v,child:Text(v.toUpperCase(),style:const TextStyle(fontSize:11)))).toList(),onChanged:(v)=>save.set(key,v)));
  Widget settings()=>Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[tag('MAKE YOUR OWN KIND OF CHAOS',cyan),const SizedBox(height:15),toggle('music','Music'),toggle('sfx','Sound effects'),toggle('haptics','Haptics'),choose('intensity','Haptic intensity',['low','normal','high'],'normal'),const Divider(),toggle('reduceMotion','Reduce motion',fallback:false),toggle('reduceFlashing','Reduce flashing'),choose('quality','Effects quality',['auto','low','high'],'auto'),toggle('analytics','Optional gameplay analytics',fallback:false),const ListTile(contentPadding:EdgeInsets.zero,title:Text('Notifications',style:TextStyle(fontSize:13)),subtitle:Text('Coming in a future quest',style:TextStyle(fontSize:10))),const Divider(),ListTile(title:const Text('Account'),trailing:const Icon(Icons.chevron_right),onTap:()=>navigate('profile')),ListTile(title:const Text('Privacy policy'),onTap:()=>navigate('privacy')),ListTile(title:const Text('Terms of service'),onTap:()=>navigate('terms')),TextButton(onPressed:()=>action(cloud.signOut),child:const Text('SIGN OUT')),TextButton(onPressed:()=>action(() async {final confirmed=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:const Text('Delete account?'),content:const Text('This removes your account and local progress. This cannot be undone.'),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('CANCEL')),TextButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('DELETE'))])); if(confirmed==true) await cloud.deleteAccount();}),child:const Text('DELETE ACCOUNT',style:TextStyle(color:Color(0xffff8f9e)))),const SizedBox(height:16),const Text('TOUCH QUEST · 1.0.0\nOriginal sounds. Original nonsense.',textAlign:TextAlign.center,style:TextStyle(fontSize:10,color:muted))]);
  Widget profile()=>Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Icon(save.badges.contains(100000)?Icons.workspace_premium:Icons.person_pin,color:gold,size:78),const SizedBox(height:14),Text(cloud.name,textAlign:TextAlign.center,style:const TextStyle(fontSize:22,color:Colors.white)),Text(save.badges.contains(100000)?'TAP GOD':save.badges.contains(1000)?'1,000 TAP CLUB':'APPRENTICE OF THE TAP',textAlign:TextAlign.center,style:const TextStyle(color:gold,fontSize:11)),const SizedBox(height:24),Row(mainAxisAlignment:MainAxisAlignment.spaceEvenly,children:[stat('LIFETIME','${save.number('lifetimeTaps')}'),stat('BEST RUN','${save.number('bestRawRun')}')]),const SizedBox(height:24),Text(cloud.status,textAlign:TextAlign.center,style:const TextStyle(fontSize:10)),const SizedBox(height:18),button('CONTINUE AS GUEST',()=>navigate('menu')),const SizedBox(height:10),button('CONTINUE WITH GOOGLE',busy?null:()=>action(()=>cloud.signIn(true)),color:muted),const SizedBox(height:10),button('CONTINUE WITH FACEBOOK',busy?null:()=>action(()=>cloud.signIn(false)),color:muted),const SizedBox(height:16),button('TAP COSMETICS',()=>navigate('skins'),color:gold),const SizedBox(height:24),const Text('ACHIEVEMENTS',style:TextStyle(color:cyan)),const SizedBox(height:10),Wrap(spacing:8,runSpacing:8,children:[for(final n in save.badges) tag(milestones[n]??'$n',gold),if(save.badges.isEmpty) const Text('Your first badge is 100 taps away.')])]);
  Widget skins()=>Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('Earn effects with real taps. No purchase required.'),const SizedBox(height:24),button('ELECTRIC CYAN',()=>save.set('skin','cyan')),const SizedBox(height:12),button(save.badges.contains(5000)?'GOLDEN TOUCH':'GOLDEN TOUCH · 5,000 TAPS',save.badges.contains(5000)?()=>save.set('skin','gold'):null,color:gold)]);
  Widget leaderboard()=>Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[tag('RAW SKILL. REAL FINGERS.',cyan),const SizedBox(height:16),const Text('Global rankings use server-validated runs. Revived runs are unranked.',style:TextStyle(fontSize:11)),const SizedBox(height:18),for(final category in ['rawTaps','score','campaign','hallOfFame']) ExpansionTile(title:Text(switch(category){'rawTaps'=>'Global best raw run','score'=>'Global best score','campaign'=>'Campaign progress',_=>'Hall of Fame'},style:const TextStyle(fontSize:13)),children:[FutureBuilder<List<Map<String,dynamic>>>(future:cloud.leaderboard(category),builder:(context,snapshot){if(snapshot.connectionState==ConnectionState.waiting) return const LinearProgressIndicator(); if(snapshot.hasError) return const Text('Rankings unavailable. Try again later.'); final entries=snapshot.data??[]; return entries.isEmpty?const Padding(padding:EdgeInsets.all(12),child:Text('No verified entries yet.',style:TextStyle(fontSize:11))):Column(children:[for(final e in entries) ListTile(title:Text(e['displayName']??'Adventurer'),trailing:Text('${e['value']}'))]);})]),const SizedBox(height:20),const Text('YOUR DEVICE · RECENT RUNS',style:TextStyle(color:gold,fontSize:11)),for(final r in save.runs.take(10)) ListTile(contentPadding:EdgeInsets.zero,title:Text('${r['rawTaps']} raw taps',style:const TextStyle(fontSize:13)),subtitle:Text('${r['mode']} · ${r['reviveCount']==0?'unverified':'revived'}',style:const TextStyle(fontSize:10)),trailing:Text('${r['score']} pts')),const SizedBox(height:15),const Text('Friends leaderboards: future update.',style:TextStyle(fontSize:10))]);
  Widget legal()=>Text(page=='privacy'?privacyText:termsText,style:const TextStyle(fontSize:13,height:1.8,color:muted));
}
const privacyText='PRIVACY POLICY — DRAFT\n\nOwner: [LEGAL OWNER]\nContact: [SUPPORT EMAIL]\nEffective: [EFFECTIVE DATE]\nJurisdiction: [COUNTRY / STATE]\n\nTouch Quest stores settings, gameplay statistics, achievements and recent runs on your device. Guest play works without registration. When configured, Firebase Authentication processes account identifiers and optional Google or Facebook profile information. Linked accounts can sync progress to Cloud Firestore. Public leaderboards display a chosen name and validated gameplay statistics.\n\nOptional Firebase Analytics is off by default. It collects aggregate run and milestone events only when enabled. Google Mobile Ads may process device identifiers and advertising interaction data after applicable consent. Provider privacy terms also apply. Web advertising is not configured. Fake comedy advertisements are game effects and collect no ad impressions.\n\nYou can change preferences, sign out, or request account deletion in Settings. Account deletion requires recent authentication and removes local data; configured server cleanup removes cloud records. Retention: [DEFINE RETENTION PERIOD]. Regional privacy rights and children’s privacy requirements: [COMPLETE BEFORE RELEASE].\n\nThis draft describes intended configured services, not legal advice. The owner must complete and review this policy before publication.';
const termsText='TERMS OF SERVICE — DRAFT\n\nOwner: [LEGAL OWNER]\nContact: [SUPPORT EMAIL]\nEffective: [EFFECTIVE DATE]\nJurisdiction: [COUNTRY / STATE]\n\nTouch Quest is an arcade game provided for personal entertainment. You may play as a guest. Online services require a connection and may be unavailable. Do not manipulate input, submit fabricated scores, abuse accounts or interfere with other players. Rankings may exclude unverified or revived runs.\n\nRewarded ads are optional. Revives are granted only after a successful reward callback and may be unavailable. No purchases are implemented. Original game art and audio belong to the project owner, subject to applicable third-party software licenses.\n\nTake breaks and use the motion, flashing and haptic settings that suit you. Account deletion removes local progress and requests removal of cloud data.\n\nWarranty, liability, dispute procedures, age eligibility and applicable local consumer rights: [OWNER AND COUNSEL TO COMPLETE]. This is a draft, not legal advice. Review before public release.';
